cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from . import views


app_name = 'shop'
urlpatterns = [
url(r'^$', views.product_list, name='product_list'),
url(r'^(?P<category_slug>[-\w]+)/$',
    views.product_list,
    name = 'product_list_by_category'),
url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
    views.product_detail,
    name = 'product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

        

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')
    
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
    
def cart_detail(request):
    cart = Cart(request)
    category = None
    categories = Category.objects.all()    
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'category': category,
                                                'categories': categories,})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}

    <p class="basket-title">Ваша корзина</p>
	<div class="backet-table">
	  <table class="detail-cart">
	    <tr class="table-top">
		  <td class="column-name" colspan="3">Наименование</td>
		  <td class="column-sum">Сумма, бел.руб.</td>
	    </tr>
		{% for item in cart %}
		  {% with product=item.product %}
		    <tr>
			  <td class="column-quantity">
			    {{ item.quantity }}
				<span>x</span> 
			  </td>
			  <td class="column-product">
			    <a href="{{ product.get_absolute_url }}">
			      {{ product.name }}
			    </a>
			  </td>
			  <td class="column-delete">
			    <a href="{% url "cart:cart_remove" product.id%}">Удалить</a>
			  </td>
			  <td class="column-price">
			    {{ item.total_price }} BYN
			  </td>
			</tr>	  
	      {% endwith %}
		{% endfor %}
		<tr class="table-bottom">
		  <td class="column-name" colspan="3">Итоговая сумма</td>
		  <td class="column-price-all">{{ cart.get_total_price }} BYN</td>
		</tr>
	  </table>
	</div>
	<div class="basket-botton">
	  <a href="{% url "orders:order_create" %}"><input class="add-basket basket-botton-buy" type="submit" value="Оформить заказ"></a>
	  <a href="{% url "shop:product_list" %}"><input class="add-basket basket-botton-menu" type="submit" value="Продолжить покупки"></a>	  	  
    </div>
{% endblock %}