cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from shop.models import Product
from django.core.validators import RegexValidator

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")
    phoneNumber = models.CharField(validators = [phoneNumberRegex], max_length = 16)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    comment = models.TextField(max_length=250, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)


    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        
    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phoneNumber', 'email', 'address', 'postal_code', 'city', 'comment']

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from shop.models import Product, Category


def order_create(request):
    cart = Cart(request)
    category = None
    categories = Category.objects.all()
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order, 'category': category,
                          'categories': categories})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form,
                  'category': category,
                  'categories': categories})

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}Checkout{% endblock %}
{% block content %}
    <div class="clearfix">
      <p class="create-title">Оформление заказа</p>
      <div class="order-info">
        <p class="order-info-title">Ваш заказ</p>
	      <ul class="order-details">
            {% for item in cart %}
              <li>				
                {{ item.quantity }} x {{ item.product.name }}
			    <span>{{ item.total_price }} BYN</span>
              </li>
            {% endfor %}
          </ul>
        <p class="order-info-title">Итог: {{ cart.get_total_price }} BYN</p>
      </div>
	  <div class="contacts-customer">
	    <form action="." method="post" class="order-form">
	      <table>
		    <tr>
		      <td class="order-form-col"><label for="id_first_name">Имя *</label></td>
			  <td><input type="text" name="first_name" maxlength="50" required id="id_first_name"></td>
		    </tr>
		    <tr>
		      <td><label for="id_last_name">Фамилия *</label></td>
		      <td><input type="text" name="last_name" maxlength="50" required id="id_last_name"></td>
		    </tr>
		    <tr>
		      <td><label for="id_phoneNumber">Номер телефона *</label></td>
			  <td><input type="text" name="phoneNumber" maxlength="16" required id="id_phoneNumber"></td>			
		    </tr>
		    <tr>
		      <td><label for="id_email">email *</label></td>
			  <td><input type="email" name="email" maxlength="254" required id="id_email"></td>			
		    </tr>
		    <tr>
		      <td><label for="id_address">Адрес *</label></td>
			  <td><input type="text" name="address" maxlength="250" required id="id_address"></td>			
		    </tr>
		    <tr>
		      <td><label for="id_postal_code">Почтовый индекс *</label></td>
			  <td><input type="text" name="postal_code" maxlength="20" required id="id_postal_code"></td>			
		    </tr>
		    <tr>
		      <td><label for="id_city">Город *</label></td>
			  <td><input type="text" name="city" maxlength="100" required id="id_city"></td>			
		    </tr>
		    <tr>
		      <td><label for="id_comment">Комментарий к заказу</label></td>
			  <td><textarea name="comment" rows="3" maxlength="250" id="id_comment"></textarea></td>			
		    </tr>
          </table>
          <p>* Поля обязательны к заполнению</p>		
	      <p><input class="confirm" type="submit" value="Оформить заказ"></p>
          {% csrf_token %}
	    </form>
	</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Thank you{% endblock %}
{% block content %}
    <div class="thanks">
      <p class="thanks-title">Спасибо за заказ!</p>
      <p class="text-title">Заказ был успешно сформирован. Ваш номер заказа <strong>{{ order.id }}</strong>.</p>
	</div>
{% endblock %}