cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views


app_name = 'shop'
urlpatterns = [
url(r'^$', views.product_list, name='product_list'),
url(r'^(?P<category_slug>[-\w]+)/$',
    views.product_list,
    name = 'product_list_by_category'),
url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
    views.product_detail,
    name = 'product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
#from django.core.urlresolvers import reverse
#from django.conf import settings
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)
        
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
        args = [self.slug])
    
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        
    def __str__(self):
        return self.name
        
                
class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
        
    def get_absolute_url(self):
        return reverse('shop:product_detail',
        args = [self.id, self.slug])
    
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return self.name


#class ProductImage(models.Model):
    #product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    #product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, default=None, related_name='images')
    #image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    
    #def get_absolute_url(self):
        #return reverse('shop:product_detail',
        #args = [self.id, self.slug])
    
    #def __str__(self):
        #return "%s" % self.id

    #class Meta:
        #verbose_name = 'Фотография'
        #verbose_name_plural = 'Фотографии'

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                  'categories': categories,
                  'products': products})


def product_detail(request, id, slug):
    category = None
    categories = Category.objects.all()
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'category': category,
                                                        'categories': categories,
                                                        'cart_product_form': cart_product_form})

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Truefeel{% endblock %}</title>
	<link href= "/static/shop/css/base.css" rel="stylesheet">
    <meta name="description" content="Шоколад и конфеты ручной работы, подарочные наборы в Могилеве">
	<meta name="keywords" content="шоколад, конфеты, трюфели, фигурки из шоколада, подарочные наборы, могилев, беларусь">	
  </head>
  <body>
    <header class="main-header clearfix">
	  <div class="container">
	    <div class="header-top">
		  <div class="logo">
		    <h1><a href="/">Truefeel</a></h1>
		  </div>
		  <div class="main-menu">
		    <ul>
              <li {% if not category %}{% endif %}>
                <a href="{% url "shop:product_list" %}">Все</a>
              </li>
              {% for c in categories %}
		        <li {% if category.slug == c.slug %}{% endif %}>              
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>				  
                </li>
	          {% endfor %}
            </ul>
		  </div>		  
		  <div class="basket">		    
		      {% with total_items=cart|length %}
			    {% if cart|length > 0 %}
			      <img class="basket-item" width="40" src="{% static "shop/img/basket.png" %}">
			      <a href="{% url "cart:cart_detail" %}">
			        {{ cart.get_total_price }} BYN
			      </a>
			    {% else %}
			       <img width="40" src="{% static "shop/img/basket.png" %}">
                   0 BYN
			    {% endif %}
			  {% endwith %}		  
		  </div>		
		</div>			  
	  </div>	  
    </header>
	<section class="my-content">
	  <div class="container">
	    <div id="content">
	      {% block content %}
          {% endblock %}	
        </div>		  
	  </div>
	</section>
	<footer class="main-footer">
	  <div class="container">
	    <div class="contacts">
	      <div class="contacts-title">Наши контакты</div>
		    <div class="contacts-info">
	          <div class="telephone">
		        <img class="telephone-item" width="17" src="{% static "shop/img/telephone.png" %}">
		        +375 29 8454334
		      </div><br>
		      <div class="email">
		        <img class="email-item" width="20" src="{% static "shop/img/email.png" %}">
		        Anastasia.Gribovskaia@gmail.com
		      </div><br>
		      <div class="instagram">		        
		        <a href="https://www.instagram.com/truefeelinlove/" class="social-btn social-btn-fb">
				<img class="instagram-item" width="17" src="{% static "shop/img/instagram.png" %}">
				truefeelinlove
				</a>
		      </div><br>
		    </div>
        </div>		  
	    <div class="copyright">Все права защищены © 2022</div>
	  </div>
	</footer>
  </body>
</html>